util.AddNetworkString("PlayerDropGear")
util.AddNetworkString("PlayerMountGear")
util.AddNetworkString("PlayerUnmountGear")
util.AddNetworkString("PlayerMountGearWithDragnDrop")
util.AddNetworkString("PlayerUnmountGearWithDragnDrop")
util.AddNetworkString("InitPlayerGear")

net.Receive("PlayerDropGear", function(_, ply)
    local MRPID = net.ReadUInt(7)
    local target = net.ReadEntity()
    local slotName = net.ReadString()
    net.Start("PlayerUnmountGear")
    net.WriteUInt(MRPID, 7)
    net.WriteEntity(target)
    net.Broadcast()
    MRP.getMRPEnt(MRPID):drop(slotName, target, ply)
end)
net.Receive("PlayerMountGearWithDragnDrop", function(_, _)
    local MRPID = net.ReadUInt(7)
    local target = net.ReadEntity()
    net.Start("PlayerMountGear")
    net.WriteUInt(MRPID, 7)
    net.WriteEntity(target)
    net.Broadcast()
end)
net.Receive("PlayerUnmountGearWithDragnDrop", function(_, _)
    local MRPID = net.ReadUInt(7)
    local target = net.ReadEntity()
    net.Start("PlayerUnmountGear")
    net.WriteUInt(MRPID, 7)
    net.WriteEntity(target)
    net.Broadcast()
end)
