MRP.Ranks = {
    [0] = { --Armée Française
        [0] = { --2REI
            [0]  = {name = "Recrue légionnaire",                short = "", appellation = "Recrue ou par le nom", bodygroupVal = 0, shoulderrank = "null"},
            [1]  = {name = "Légionnaire",                       short = "SDT", appellation = "Soldat ou par le nom", bodygroupVal = 1, shoulderrank = "materials/gui/shoulderrank/legion/sdt.png"},
            [2]  = {name = "Légionnaire de première classe",    short = "1CL", appellation = "Soldat, première classe ou par le nom", bodygroupVal = 2, shoulderrank = "materials/gui/shoulderrank/legion/1cl.png"},
            [3]  = {name = "Caporal",                           short = "CPL", appellation = "Caporal", bodygroupVal = 3, shoulderrank = "materials/gui/shoulderrank/legion/cpl.png"},
            [4]  = {name = "Caporal-chef",                      short = "CCH", appellation = "Caporal-chef", bodygroupVal = 4, shoulderrank = "materials/gui/shoulderrank/legion/infantry/cch.png"},
            [5]  = {name = "Sergent",                           short = "SGT", appellation = "Sergent", bodygroupVal = 6, shoulderrank = "materials/gui/shoulderrank/legion/infantry/sgt.png"},
            [6]  = {name = "Sergent-chef",                      short = "SCH", appellation = "Chef", bodygroupVal = 7, shoulderrank = "materials/gui/shoulderrank/legion/infantry/sch.png"},
            [7]  = {name = "Adjudant",                          short = "ADJ", appellation = "Mon adjudant ou adjudant (féminin)", bodygroupVal = 8, shoulderrank = "materials/gui/shoulderrank/legion/infantry/adj.png"},
            [8]  = {name = "Adjudant-chef",                     short = "ADC", appellation = "Mon adjudant chef ou adjudant chef (féminin)", bodygroupVal = 9, shoulderrank = "materials/gui/shoulderrank/legion/infantry/adc.png"},
            [9]  = {name = "Major",                             short = "MAJ", appellation = "Major", bodygroupVal = 10, shoulderrank = "materials/gui/shoulderrank/legion/infantry/maj.png"},
            [10] = {name = "Aspirant",                          short = "ASP", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 11, shoulderrank = "materials/gui/shoulderrank/legion/infantry/slt.png"},
            [11] = {name = "Sous-lieutenant",                   short = "SLT", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 12, shoulderrank = "materials/gui/shoulderrank/legion/infantry/slt.png"},
            [12] = {name = "Lieutenant",                        short = "LTN", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 13, shoulderrank = "materials/gui/shoulderrank/legion/infantry/ltn.png"},
            [13] = {name = "Capitaine",                         short = "CNE", appellation = "Mon capitaine ou capitaine (féminin)", bodygroupVal = 14, shoulderrank = "materials/gui/shoulderrank/legion/infantry/cne.png"},
            [14] = {name = "Chef de bataillon",                 short = "CBA", appellation = "Mon commandant ou commandant (féminin)", bodygroupVal = 15, shoulderrank = "materials/gui/shoulderrank/legion/infantry/cba.png"},
            [15] = {name = "Lieutenant-colonel",                short = "LCL", appellation = "Mon colonel ou colonel (féminin)", bodygroupVal = 16, shoulderrank = "materials/gui/shoulderrank/legion/infantry/lcl.png"},
            [16] = {name = "Colonel",                           short = "COL", appellation = "Mon colonel ou colonel (féminin)", bodygroupVal = 17, shoulderrank = "materials/gui/shoulderrank/legion/infantry/col.png"}
        },
        [1] = { --5RHC
            [0]  = {name = "Recrue pilote",                     short = "", appellation = "Recrue ou par le nom", bodygroupVal = 0, shoulderrank = "null"},
            [1]  = {name = "Maréchal des logis",                short = "MDL", appellation = "Maréchal des logis", bodygroupVal = 5, shoulderrank = "materials/gui/shoulderrank/alat/mdl.png"},
            [2]  = {name = "Maréchal des logis-chef",           short = "MCH", appellation = "Chef", bodygroupVal = 6, shoulderrank = "materials/gui/shoulderrank/alat/mch.png"},
            [3]  = {name = "Adjudant",                          short = "ADJ", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 7, shoulderrank = "materials/gui/shoulderrank/alat/adj.png"},
            [4]  = {name = "Adjudant-chef",                     short = "ADC", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 8, shoulderrank = "materials/gui/shoulderrank/alat/adc.png"},
            [5]  = {name = "Major",                             short = "MAJ", appellation = "Major", bodygroupVal = 9, shoulderrank = "materials/gui/shoulderrank/alat/maj.png"},
            [6]  = {name = "Elève officier",                    short = "EO", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 10, shoulderrank = "materials/gui/shoulderrank/alat/eo.png"},
            [7]  = {name = "Aspirant",                          short = "ASP", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 10, shoulderrank = "materials/gui/shoulderrank/alat/asp.png"},
            [8]  = {name = "Sous-lieutenant",                   short = "SLT", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 11, shoulderrank = "materials/gui/shoulderrank/alat/slt.png"},
            [9]  = {name = "Lieutenant",                        short = "LTN", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 12, shoulderrank = "materials/gui/shoulderrank/alat/ltn.png"},
            [10] = {name = "Capitaine",                         short = "CNE", appellation = "Mon capitaine ou capitaine (féminin)", bodygroupVal = 13, shoulderrank = "materials/gui/shoulderrank/alat/cne.png"},
            [11] = {name = "Chef d'escadrons'",                 short = "CEN", appellation = "Mon commandant ou commandant (féminin)", bodygroupVal = 14, shoulderrank = "materials/gui/shoulderrank/alat/cen.png"},
            [12] = {name = "Lieutenant-colonel",                short = "LCL", appellation = "Mon colonel ou colonel (féminin)", bodygroupVal = 15, shoulderrank = "materials/gui/shoulderrank/alat/lcl.png"},
            [13] = {name = "Colonel",                           short = "COL", appellation = "Mon colonel ou colonel (féminin)", bodygroupVal = 16, shoulderrank = "materials/gui/shoulderrank/alat/col.png"}

        },
        [2] = { --1REC
            [0] = {name = "Recrue cavalier",                    short = "", appellation = "Recrue ou par le nom", bodygroupVal = 0, shoulderrank = "null"},
            [1] = {name = "Cavalier",                           short = "SDT", appellation = "Soldat ou par le nom", bodygroupVal = 1, shoulderrank = "materials/gui/shoulderrank/legion/sdt.png"},
            [2] = {name = "Cavalier de première classe",        short = "1CL", appellation = "Soldat, première classe ou par le nom", bodygroupVal = 2, shoulderrank = "materials/gui/shoulderrank/legion/1cl.png"},
            [3] = {name = "Brigadier",                          short = "BRI", appellation = "Brigadier", bodygroupVal = 3, shoulderrank = "materials/gui/shoulderrank/legion/cpl.png"},
            [4] = {name = "Brigadier-chef",                     short = "BCH", appellation = "Brigadier-chef", bodygroupVal = 4, shoulderrank = "materials/gui/shoulderrank/legion/cavalry/bch.png"},
            [5] = {name = "Brigadier-chef de première classe",  short = "BC1", appellation = "Brigadier-chef", bodygroupVal = 5, shoulderrank = "materials/gui/shoulderrank/legion/cavalry/bch.png"},
            [6] = {name = "Maréchal des logis",                 short = "MDL", appellation = "Maréchal des logis", bodygroupVal = 6, shoulderrank = "materials/gui/shoulderrank/legion/cavalry/mdl.png"},
            [7] = {name = "Maréchal des logis-chef",            short = "MCH", appellation = "Chef", bodygroupVal = 7, shoulderrank = "materials/gui/shoulderrank/legion/cavalry/mch.png"},
            [8] = {name = "Adjudant",                           short = "ADJ", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 8, shoulderrank = "materials/gui/shoulderrank/legion/cavalry/adj.png"},
            [9] = {name = "Adjudant-chef",                      short = "ADC", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 9, shoulderrank = "materials/gui/shoulderrank/legion/cavalry/adc.png"},
            [10] = {name = "Major",                             short = "MAJ", appellation = "Major", bodygroupVal = 10, shoulderrank = "materials/gui/shoulderrank/legion/cavalry/maj.png"},
            [11] = {name = "Aspirant",                          short = "ASP", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 11, shoulderrank = "materials/gui/shoulderrank/legion/cavalry/slt.png"},
            [12] = {name = "Sous-lieutenant",                   short = "SLT", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 12, shoulderrank = "materials/gui/shoulderrank/legion/cavalry/slt.png"},
            [13] = {name = "Lieutenant",                        short = "LTN", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 13, shoulderrank = "materials/gui/shoulderrank/legion/cavalry/ltn.png"},
            [14] = {name = "Capitaine",                         short = "CNE", appellation = "Mon capitaine ou capitaine (féminin)", bodygroupVal = 14, shoulderrank = "materials/gui/shoulderrank/legion/cavalry/cne.png"},
            [15] = {name = "Chef d'escadrons",                  short = "CEN", appellation = "Mon commandant ou commandant (féminin)", bodygroupVal = 15, shoulderrank = "materials/gui/shoulderrank/legion/cavalry/cen.png"},
            [16] = {name = "Lieutenant-colonel",                short = "LCL", appellation = "Mon colonel ou colonel (féminin)", bodygroupVal = 16, shoulderrank = "materials/gui/shoulderrank/legion/cavalry/lcl.png"},
            [17] = {name = "Colonel",                           short = "COL", appellation = "Mon colonel ou colonel (féminin)", bodygroupVal = 17, shoulderrank = "materials/gui/shoulderrank/legion/cavalry/col.png"}
        },
        [3] = { --1RPIMA
            [0]  = {name = "Recrue marsouin",                   short = "", appellation = "Recrue ou par le nom", bodygroupVal = 0, shoulderrank = "null"},
            [1]  = {name = "Marsouin",                          short = "SDT", appellation = "Soldat ou par le nom", bodygroupVal = 1, shoulderrank = "materials/gui/shoulderrank/rpima/sdt.png"},
            [2]  = {name = "Marsouin de première classe",       short = "1CL", appellation = "Soldat, première classe ou par le nom", bodygroupVal = 2, shoulderrank = "materials/gui/shoulderrank/rpima/1cl.png"},
            [3]  = {name = "Caporal",                           short = "CPL", appellation = "Caporal", bodygroupVal = 3, shoulderrank = "materials/gui/shoulderrank/rpima/cpl.png"},
            [4]  = {name = "Caporal-chef",                      short = "CCH", appellation = "Caporal-chef", bodygroupVal = 4, shoulderrank = "materials/gui/shoulderrank/rpima/cch.png"},
            [5]  = {name = "Sergent",                           short = "SGT", appellation = "Sergent", bodygroupVal = 6, shoulderrank = "materials/gui/shoulderrank/rpima/sgt.png"},
            [6]  = {name = "Sergent-chef",                      short = "SCH", appellation = "Chef", bodygroupVal = 7, shoulderrank = "materials/gui/shoulderrank/rpima/sch.png"},
            [7]  = {name = "Adjudant",                          short = "ADJ", appellation = "Mon adjudant ou adjudant (féminin)", bodygroupVal = 8, shoulderrank = "materials/gui/shoulderrank/rpima/adj.png"},
            [8]  = {name = "Adjudant-chef",                     short = "ADC", appellation = "Mon adjudant chef ou adjudant chef (féminin)", bodygroupVal = 9, shoulderrank = "materials/gui/shoulderrank/rpima/adc.png"},
            [9]  = {name = "Major",                             short = "MAJ", appellation = "Major", bodygroupVal = 10, shoulderrank = "materials/gui/shoulderrank/rpima/maj.png"},
            [10] = {name = "Aspirant",                          short = "ASP", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 11, shoulderrank = "materials/gui/shoulderrank/rpima/slt.png"},
            [11] = {name = "Sous-lieutenant",                   short = "SLT", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 12, shoulderrank = "materials/gui/shoulderrank/rpima/slt.png"},
            [12] = {name = "Lieutenant",                        short = "LTN", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 13, shoulderrank = "materials/gui/shoulderrank/rpima/ltn.png"},
            [13] = {name = "Capitaine",                         short = "CNE", appellation = "Mon capitaine ou capitaine (féminin)", bodygroupVal = 14, shoulderrank = "materials/gui/shoulderrank/rpima/cne.png"},
            [14] = {name = "Chef de bataillon",                 short = "CBA", appellation = "Mon commandant ou commandant (féminin)", bodygroupVal = 15, shoulderrank = "materials/gui/shoulderrank/rpima/cba.png"},
            [15] = {name = "Lieutenant-colonel",                short = "LCL", appellation = "Mon colonel ou colonel (féminin)", bodygroupVal = 16, shoulderrank = "materials/gui/shoulderrank/rpima/lcl.png"},
            [16] = {name = "Colonel",                           short = "COL", appellation = "Mon colonel ou colonel (féminin)", bodygroupVal = 17, shoulderrank = "materials/gui/shoulderrank/rpima/col.png"}

        }
    },
    [1] = { --Armée rebelle
        [0] = {
            [0] = {name = "Recrue soldat",                    short = "", appellation = "Recrue ou par le nom", bodygroupVal = 0, shoulderrank = "null"},
            [1] = {name = "Soldat",                           short = "SDT", appellation = "Soldat ou par le nom", bodygroupVal = 1, shoulderrank = "materials/null.vmt"},
            [2] = {name = "Soldat de première classe",        short = "1CL", appellation = "Soldat, première classe ou par le nom", bodygroupVal = 2, shoulderrank = "materials/null.vmt"},
            [3] = {name = "Caporal",                            short = "CPL", appellation = "Caporal", bodygroupVal = 3, shoulderrank = "materials/null.vmt"},
            [4] = {name = "Caporal-chef",                       short = "CCH", appellation = "Caporal-chef", bodygroupVal = 4, shoulderrank = "materials/null.vmt"},
            [5] = {name = "Caporal-chef de première classe",    short = "CC1", appellation = "Caporal-chef", bodygroupVal = 5, shoulderrank = "materials/null.vmt"},
            [6] = {name = "Sergent",                            short = "SGT", appellation = "Sergent", bodygroupVal = 6, shoulderrank = "materials/null.vmt"},
            [7] = {name = "Sergent-chef",                       short = "SCH", appellation = "Chef", bodygroupVal = 7, shoulderrank = "materials/null.vmt"},
            [8] = {name = "Adjudant",                           short = "ADJ", appellation = "Mon adjudant ou adjudant (féminin)", bodygroupVal = 8, shoulderrank = "materials/null.vmt"},
            [9] = {name = "Adjudant-chef",                      short = "ADC", appellation = "Mon adjudant chef ou adjudant chef (féminin)", bodygroupVal = 9, shoulderrank = "materials/null.vmt"},
            [10] = {name = "Major",                             short = "MAJ", appellation = "Major", bodygroupVal = 10, shoulderrank = "materials/null.vmt"},
            [11] = {name = "Aspirant",                          short = "ASP", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 11, shoulderrank = "materials/null.vmt"},
            [12] = {name = "Sous-lieutenant",                   short = "SLT", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 12, shoulderrank = "materials/null.vmt"},
            [13] = {name = "Lieutenant",                        short = "LTN", appellation = "Mon lieutenant ou lieutenant (féminin)", bodygroupVal = 13, shoulderrank = "materials/null.vmt"},
            [14] = {name = "Capitaine",                         short = "CNE", appellation = "Mon capitaine ou capitaine (féminin)", bodygroupVal = 14, shoulderrank = "materials/null.vmt"},
            [15] = {name = "Chef de bataillon",                 short = "CBA", appellation = "Mon commandant ou commandant (féminin)", bodygroupVal = 15, shoulderrank = "materials/null.vmt"},
            [16] = {name = "Lieutenant-colonel",                short = "LCL", appellation = "Mon colonel ou colonel (féminin)", bodygroupVal = 16, shoulderrank = "materials/null.vmt"},
            [17] = {name = "Colonel",                           short = "COL", appellation = "Mon colonel ou colonel (féminin)", bodygroupVal = 17, shoulderrank = "materials/null.vmt"}
        }
    }
}