net.Receive("MRPClientPutNVGsOn", function(len, ply)
    ply:SetNWBool("NVGsOn", true)
    net.Start("MRPPlayerTakeOnNVGs")
    net.WriteUInt(ply:UserID(), 16)
    net.Broadcast()
end)
net.Receive("MRPClientPutNVGsOff", function(len, ply)
    ply:SetNWBool("NVGsOn", false)
    net.Start("MRPPlayerTakeOffNVGs")
    net.WriteUInt(ply:UserID(), 16)
    net.Broadcast()
end)